# machine: Topic Development Kit with Zynq Ultrascale 6EG

MACHINE_BOARD = "topic-miami-florida-gen"
FPGA_FAMILY = "xczu9eg"
FPGA_FAMILY_SHORT = "xczu"
FPGA_PART = "xczu9eg-ffvb1156-1-i"

require conf/machine/include/topic-miamimp-florida-gen.inc

TOPIC_XSA_DESIGN_SHA256SUM = "1dcf96e8512b487eaf4e01d8dd8d316d16447dbdbe056296fefb124eb46c848c"
