# machine: Topic Development Kit with Zynq Ultrascale 6EG

MACHINE_BOARD = "topic-miami-florida-gen"
FPGA_FAMILY = "xczu15eg"
FPGA_FAMILY_SHORT = "xczu"
FPGA_PART = "xczu15eg-ffvb1156-1-i"

require conf/machine/include/topic-miamimp-florida-gen.inc

TOPIC_XSA_DESIGN_SHA256SUM = "6dad11189cc409916d0c3076860efdb9b01f3e677b50265769464e6a16888aab"
