# machine: Topic Development Kit with Zynq Ultrascale 6EG

MACHINE_BOARD = "topic-miami-florida-gen"
FPGA_FAMILY = "xczu15eg"
FPGA_FAMILY_SHORT = "xczu"
FPGA_PART = "xczu15eg-ffvb1156-1-i"

require conf/machine/include/topic-miamimp-florida-gen.inc

TOPIC_XSA_DESIGN_SHA256SUM = "3fd9594954d9683f9505dcdae60bfe7565a496c6bd99470c275d996db0a60a37"
