# machine: Topic Development Kit with Zynq Ultrascale 6EG

MACHINE_BOARD = "topic-miami-florida-gen"
FPGA_FAMILY = "xczu9eg"
FPGA_FAMILY_SHORT = "xczu"
FPGA_PART = "xczu9eg-ffvb1156-1-i"

require conf/machine/include/topic-miamimp-florida-gen.inc

TOPIC_XSA_DESIGN_SHA256SUM = "cf727970195b97640f2b77f1e64128cc11678da579d0a11e0a52e0956c4a56bd"
