# machine: Topic Development Kit with Zynq Ultrascale 6EG

MACHINE_BOARD = "topic-miami-florida-gen"
FPGA_FAMILY = "xczu6eg"
FPGA_FAMILY_SHORT = "xczu"
FPGA_PART = "xczu6eg-ffvb1156-1-i"

require conf/machine/include/topic-miamimp-florida-gen.inc

TOPIC_XSA_DESIGN_SHA256SUM = "13ace8a89bdb2c00a35b0dd666aa30af150c4783b01c11a522bdab37baa529fe"
