#@TYPE: Machine
#@NAME: tepzu9
#@DESCRIPTION: Machine configuration for the tepzu9 boards.

FPGA_FAMILY = "xczu9eg"
FPGA_PART = "xczu9eg-ffvb1156-1-i"

require conf/machine/include/tspzu.inc

# Original SDT artifacts URL
SDT_URI = "http://fpga-server.local/downloads/fpga/sdt-tepzu9-280+38e5dd1.tar.xz"
SDT_URI[sha256sum] = "188748f2b2c383a2fd6211493538873357aae57fe1e4aee57a652355e809c2be"

# Devicetree stuff
BOARD_PL_REFERENCE = "dtb-tepzu-reference"

MACHINE_WIFI_DRIVERS = "\
	kernel-module-cfg80211 \
	kernel-module-mac80211 \
	kernel-module-libarc4 \
	kernel-module-iwlwifi \
	kernel-module-iwlmvm \
	linux-firmware-iwlwifi-ax200 \
	"
MACHINE_BT_DRIVERS = "\
	kernel-module-bluetooth \
	kernel-module-btmrvl \
	kernel-module-btusb \
	linux-firmware-ibt-20 \
	"

# Extra packages to install for the board
MACHINE_EXTRA_RRECOMMENDS += "\
	kernel-module-lima \
	kernel-module-u-ether \
	kernel-module-usb-f-ecm \
	kernel-module-usb-f-ecm-subset \
	kernel-module-usb-f-mass-storage \
	kernel-module-usb-f-rndis \
	"

MACHINE_FEATURES_EXTRA += "usbhost usbgadget ethernet powerkey screen"
