# machine: Topic Testboard Plus with Zynq Ultrascale 9EG

FPGA_FAMILY = "xczu9eg"
FPGA_PART = "xczu9eg-ffvb1156-1-i"

require conf/machine/include/ttpzu.inc

TOPIC_XSA_DESIGN_SHA256SUM = "008a738ed47618b423b51265e5a81a53567c014004cba19f01c9a638332f402b"
