#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          networking
# Required-Start:    mountvirtfs $local_fs
# Required-Stop:     $local_fs
# Should-Start:      ifupdown
# Should-Stop:       ifupdown
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Raise network interfaces.
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

case "$1" in
start)
	echo -n "Configuring network interfaces... "
	ifup -a > /dev/null 2>&1 &
	echo "(background)"
	;;

stop)
	echo -n "Deconfiguring network interfaces... "
	ifdown -a
	echo "done."
	;;

force-reload|restart)
	echo "Running $0 $1 is deprecated because it may not enable again some interfaces"
	echo "Reconfiguring network interfaces... "
	ifdown -a || true
	ifup -a
	echo "done."
	;;

*)
	echo "Usage: /etc/init.d/networking {start|stop}"
	exit 1
	;;
esac

exit 0

